create_player flow into main for the weekend warriors
CMPUT301W23T13/QRiffic pull request #70
Opened 2023-03-03 22:00 UTC by cubeof2

I have made a lot of base changes that all should work off of before doing weekend work.

2023-03-03 22:08 UTC, Kunal112003 approved these changes
everything looks great!!

2023-03-03 23:28 UTC, lukeschultz3 requested changes
Add functionality to fetch and uniqueID that already exists

2023-03-04 02:55 UTC, cubeof2 commented
updated per Luke's request.
Right now the solution is a hack since I do not know how to load the default fragment with a bundle.  This will unblock everyone though.

2023-03-04 03:03 UTC, lukeschultz3 approved these changes

2023-03-04 03:03 UTC, merged